apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: $(echo -n '{"auths":{"https://index.docker.io/v1/":{"username":${{ secrets.DOCKER_USERNAME }},"password":${{ secrets.DOCKER_PASSWORD }},"email":"giri.soumyakanti@gmail.com"}}}' | base64)